name: Upload to pypi

on:
  push:
    branches: [ main ]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vault-dump
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Run Tests'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - name: Install pypa/build
      run: python -m pip install build
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
