name: Run Tests and try upload to pypi if push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/test.yaml
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: event_name
        run: echo ${{github.event_name}}
      - name: ref
        run: echo ${{github.ref}}
      - name: all
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  pypi-publish:
    if: github.event_name == 'push'
    name: Upload release to PyPI
    needs: [tests] # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vault-dump
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Install pypa/build
      run: python -m pip install build
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
